# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_sandbox.ipynb",
         "HelloSayer": "00_sandbox.ipynb"}

modules = ["core.py"]

doc_url = "https://johsieders.github.io/fttp/"

git_url = "https://github.com/johsieders/fttp/tree/master/"

def custom_doc_links(name): return None
